tracks_list = [
    {"location": "Brands Hatch", "layout": ["Grand Prix Circuit", "Indy Circuit"]},
    {"location": "Circuit de Barcelona-Catalunya", "layout": ["Grand Prix Circuit", "National Circuit", "National Circuit Alt"]},
    {"location": "Circuit de Spa-Francorchamps", "layout": ["Full Circuit"]},
    {"location": "Daytona International Speedway", "layout": ["Sports Car Circuit", "Tri-Oval Circuit"]},
    {"location": "Eaglerock Speedway", "layout": ["Oval Circuit", "Club Circuit", "Club Circuit Reverse"]},
    {"location": "Grand Oak Raceway", "layout": ["National Circuit", "Club Circuit", "National Circuit Reverse"]},
    {"location": "Hakone", "layout": ["Grand Prix Circuit", "Club Circuit", "Club Circuit Reverse"]},
    {"location": "Hockenheimring", "layout": ["Full Circuit", "National Circuit", "Short Circuit"]},
    {"location": "Homestead-Miami Speedway", "layout": ["Speedway Circuit", "Road Circuit"]},
    {"location": "Indianapolis Motor Speedway", "layout": ["The Brickyard Speedway", "Grand Prix Circuit"]},
    {"location": "Kyalami Grand Prix Circuit", "layout": ["Grand Prix Circuit"]},
    {"location": "Le Mans - Circuit International De La Sarthe", "layout": ["Full Circuit", "Old Mulsanne Circuit"]},
    {"location": "Lime Rock Park", "layout": ["Full Circuit", "South Chicane", "Full Circuit Alt"]},
    {"location": "Mobil 1 Presents Maple Valley", "layout": ["Full Circuit", "Short Circuit", "Short Circuit Reverse"]},
    {"location": "Michelin Raceway Road Atlanta", "layout": ["Grand Prix Course", "Short Course"]},
    {"location": "Mid-Ohio Sports Car Course", "layout": ["Sports Car Circuit", "Short Circuit"]},
    {"location": "Mount Panorama Circuit", "layout": ["Bathurst Circuit"]},
    {"location": "Mugello Circuit", "layout": ["Full Circuit", "Club Circuit"]},
    {"location": "Nürburgring", "layout": ["Full Circuit", "Nordschleife", "GP Circuit", "Sprint Circuit"]},
    {"location": "Road America", "layout": ["Full Circuit", "East Route"]},
    {"location": "Sebring International Raceway", "layout": ["Full Circuit", "Short Circuit"]},
    {"location": "Silverstone Circuit", "layout": ["Grand Prix Circuit", "National Circuit", "International Circuit"]},
    {"location": "Sunset Peninsula Raceway", "layout": ["Full Circuit", "Club Circuit", "Full Circuit Reverse", "Club Circuit Reverse", "Speedway"]},
    {"location": "Suzuka Circuit", "layout": ["Full Circuit", "East Circuit"]},
    {"location": "Virginia International Raceway", "layout": ["Full", "North", "South", "Grand West", "Grand East"]},
    {"location": "Watkins Glen International Speedway", "layout": ["Full Circuit", "Short Circuit"]},
    {"location": "WeatherTech Raceway Laguna Seca", "layout": ["Full Circuit", "Short Circuit"]},
    {"location": "Yas Marina Circuit", "layout": ["Full Circuit", "North Circuit", "South Circuit", "North Corkscrew"]}
]

weather_list = [
    "Variable Dry", 
    "Variable Wet", 
    "Rain at End", 
    "Rain at Start", 
    "Clear", 
    "Mostly Clear", 
    "Partly Cloudy", 
    "Cloudy", 
    "Looming Clouds", 
    "Thunderclouds", 
    "Thin Haze", 
    "Patchy Fog", 
    "Dense Fog", 
    "Overcast Dry", 
    "Overcast Wet", 
    "Drizzle", 
    "Light Rain", 
    "Moderate Rain", 
    "Heavy Rain", 
    "Thunderstorm", 
    "Rainstorm"
    ]

time_of_day = [
    "Sunrise", 
    "Morning", 
    "Late Morning", 
    "Noon", 
    "Afternoon", 
    "Late Afternoon", 
    "Evening", 
    "Sunset", 
    "Night", 
    "Midnight"
    ]