tracks_list = [
    {"location": "Brands Hatch", "layout": ["Grand Prix Circuit", "Indy Circuit"]},
    {"location": "Circuit de Barcelona-Catalunya", "layout": ["Catalunya Grand Prix Circuit", "Track_layout_2"]},
    {"location": "Circuit de Spa-Francorchamps", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Circuit des 24 Heures du Mans", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Daytona International Speedway", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Eaglerock Speedway", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Grand Oak Raceway", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Hakone Circuit", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Hockenheimring", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Homestead-Miami Speedway", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Indianapolis Motor Speedway", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Kyalami Grand Prix Circuit", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Lime Rock Park", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Michelin Raceway Road Atlanta", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Mid-Ohio Sports Car Course", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Mobil 1 Presents Maple Valley", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Mount Panorama Circuit", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Mugello Circuit", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Nürburgring", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Road America", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Sebring International Raceway", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Silverstone Circuit", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Sunset Peninsula Raceway", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Suzuka Circuit", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Virginia International Raceway", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Watkins Glen International", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "WeatherTech Raceway Laguna Seca", "layout": ["Track_layout_1", "Track_layout_2"]},
    {"location": "Yas Marina Circuit", "layout": ["Track_layout_1", "Track_layout_2"]}
]

weather_list = ["Clear", "Rain", "Fog", "Overcast"]